apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  selector:
    app: spark
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
spec:
  selector:
    app: model-serving
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
