apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
spec:
  template:
    spec:
      containers:
      - name: spark-container
        image: your-spark-image:latest
        command: ["spark-submit"]
        args:
          - "--class"
          - "org.apache.spark.examples.SparkPi"
          - "/opt/spark/examples/jars/spark-examples_2.12-3.4.1.jar"
          - "1000"
      restartPolicy: OnFailure
